# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT
---
# file: iot.yml - tasks to deploy IoT components to the destination edges.

# Deploy Azure Edge(s)
- hosts: azure-edge
  become: yes
  tags: azure
  roles:
    - { role: vmware.azure-edge }

# Deploy Greengrass Core(s)
- hosts: greengrass-core
  become: yes
  tags: greengrass,greengrass-core
#  roles:
#    - { role: greengrass-core }
