# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: vmware.azure-iot
  src: git+ssh://git@gitlab.eng.vmware.com/vmworld2018/ansible-role-azure-iot.git
- name: vmware.azure-edge
  src: git+ssh://git@gitlab.eng.vmware.com/vmworld2018/ansible-role-azure-edge.git
