# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: vmware.ansible_role_greengrass_awscli
  src: vmware.ansible_role_greengrass_awscli
- name: vmware.awscli
  src: vmware.ansible_role_greengrass_awscli
- name: huxoll.azure-cli
  src: huxoll.azure-cli
