# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: vmware.azure-iot
  src: https://gitlab.eng.vmware.com/vmworld2018/ansible-role-azure-iot/-/jobs/167214/artifacts/raw/packages/azure-iot.tar.gz?job=package_role&private_token=8j6mr5tYpCxy1TD_Aoaf
- name: vmware.azure-edge
  src: https://gitlab.eng.vmware.com/vmworld2018/ansible-role-azure-edge/-/jobs/167368/artifacts/raw/packages/azure-edge.tar.gz?job=package_role&private_token=8j6mr5tYpCxy1TD_Aoaf
