# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT
---
- name: vmware.ansible_role_greengrass_awscli
  src: vmware.ansible_role_greengrass_awscli
- name: vmware.awscli
  src: vmware.ansible_role_greengrass_awscli
- name: huxoll.azure-cli
  src: huxoll.azure-cli
- name: vmware.azure-edge
  src: vmware.azure_edge
- name: vmware.azure-iot
  src: vmware.azure_iot
